#!/usr/bin/env bash

set -e


ORG_PATH="github.com/murat1985"
REPO_PATH="${ORG_PATH}/bagpipe-cni"

if [ ! -h src/${REPO_PATH} ]; then
  echo "creating dir gopath/src/${ORG_PATH}"
  mkdir -p src/${ORG_PATH}
  echo "link to ../../../.. gopath/src/${REPO_PATH}"
  ln -s ../../../.. src/${REPO_PATH} || exit 255
fi

ls vendor/github.com | while read vendor; do ln -s ${PWD}/vendor/github.com/$vendor src/github.com/$vendor; done

export GO15VENDOREXPERIMENT=1
export GOBIN=${PWD}/bin
export GOPATH=${PWD}
echo "Current dir ${PWD}"
echo "GOPATH=${GOPATH}"

go get github.com/onsi/gomega
go get github.com/onsi/ginkgo

sudo -E bash -c "umask 0; PATH=$GOROOT/bin:$GOBIN:$PATH go test"
